---------LAB-5---------

------------------------------------ALTER, RENAME OPERATION-------------------------------------

-------PART-A

--1. Add two more columns City VARCHAR (20) and Pincode INT.
	ALTER TABLE DEPOSIT
	ADD CITY VARCHAR(20),
		PINCODE INT

	SELECT * FROM DEPOSIT


--2. Add column state VARCHAR(20).
	ALTER TABLE DEPOSIT
	ADD STATE VARCHAR(20)

	SELECT * FROM DEPOSIT


--3. Change the size of CNAME column from VARCHAR (50) to VARCHAR (35).
	ALTER TABLE DEPOSIT
	ALTER COLUMN CNAME VARCHAR(35)

	SELECT * FROM DEPOSIT


--4. Change the data type DECIMAL to INT in amount Column.
	ALTER TABLE DEPOSIT
	ALTER COLUMN AMOUNT INT

	SELECT * FROM DEPOSIT


--5. Delete Column City from the DEPOSIT table.
	ALTER TABLE DEPOSIT
	DROP COLUMN CITY

	SELECT * FROM DEPOSIT


--6. Rename Column ActNo to ANO.
	SP_RENAME 'DEPOSIT.ACTNO', 'ANO'

	SELECT * FROM DEPOSIT


--7. Change name of table DEPOSIT to DEPOSIT_DETAIL.
	SP_RENAME 'DEPOSIT', 'DEPOSIT_DETAIL'

	SELECT * FROM DEPOSIT_DETAIL



-------PART-B

--1. Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table.
	SP_RENAME 'DEPOSIT_DETAIL.ADATE', 'AOPENDATE'

	SELECT * FROM DEPOSIT_DETAIL


--2. Delete Column AOPENDATE from the DEPOSIT_DETAIL table.
	ALTER TABLE DEPOSIT_DETAIL
	DROP COLUMN AOPENDATE

	SELECT * FROM DEPOSIT_DETAIL


--3. Rename Column CNAME to CustomerName.
	SP_RENAME 'DEPOSIT_DETAIL.CNAME', 'CUSTOMERNAME'

	SELECT * FROM DEPOSIT_DETAIL


--4. Add Column country.
	ALTER TABLE DEPOSIT_DETAIL
	ADD COUNTRY VARCHAR(20)

	SELECT * FROM DEPOSIT_DETAIL



-------PART-C

CREATE TABLE STUDENT_DETAIL(
	ENROLLMENT_NO VARCHAR(20),
	NAME VARCHAR(25),
	CPI DECIMAL(5,2),
	BIRTHDATE DATETIME
);

--1. Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null).
	ALTER TABLE STUDENT_DETAIL
	ADD CITY VARCHAR(20) NOT NULL,
		BACKLOG INT

	SELECT * FROM STUDENT_DETAIL


--2. Add column department VARCHAR (20) Not Null.
	ALTER TABLE STUDENT_DETAIL
	ADD DEPARTMENT VARCHAR(20) NOT NULL

	SELECT * FROM STUDENT_DETAIL


--3. Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35).
	ALTER TABLE STUDENT_DETAIL
	ALTER COLUMN NAME VARCHAR(35)

	SELECT * FROM STUDENT_DETAIL


--4. Change the data type DECIMAL to INT in CPI Column.
	ALTER TABLE STUDENT_DETAIL
	ALTER COLUMN CPI INT

	SELECT * FROM STUDENT_DETAIL


--5. Delete Column City from the student_detail table.
	ALTER TABLE STUDENT_DETAIL
	DROP CONSTRAINT DF__STUDENT_DE__CITY__5BE2A6F2

	ALTER TABLE STUDENT_DETAIL
	DROP COLUMN CITY

	SELECT * FROM STUDENT_DETAIL


--6. Rename Column Enrollment_No to ENO.
	SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO', 'ENO'

	SELECT * FROM STUDENT_DETAIL


--7. Change name of table student_detail to STUDENT_MASTER.
	SP_RENAME 'STUDENT_DETAIL', 'STUDENT_MASTER'

	SELECT * FROM STUDENT_MASTER




------------------------------------DELETE, TRUNCATE, DROP OPERATION-------------------------------------

-------PART-A

--1. Delete all the records of DEPOSIT_DETAIL table having amount less than and equals to 4000.
	DELETE FROM DEPOSIT_DETAIL
	WHERE AMOUNT <= 4000

	SELECT * FROM DEPOSIT_DETAIL


--2. Delete all the accounts CHANDI BRANCH.
	DELETE FROM DEPOSIT_DETAIL
	WHERE BNAME = 'CHANDI'

	SELECT * FROM DEPOSIT_DETAIL
	

--3. Delete all the accounts having account number (ANO) is greater than 102 and less than 105.
	DELETE FROM DEPOSIT_DETAIL
	WHERE ANO BETWEEN 102 AND 105

	SELECT * FROM DEPOSIT_DETAIL


--4. Delete all the accounts whose branch is ‘AJNI’ or ‘POWAI’
	DELETE FROM DEPOSIT_DETAIL
	WHERE BNAME IN('AJNI', 'POWAI')

	SELECT * FROM DEPOSIT_DETAIL


--5. Delete all the accounts whose account number is NULL.
	DELETE FROM DEPOSIT_DETAIL
	WHERE ANO IS NULL

	SELECT * FROM DEPOSIT_DETAIL


--6. Delete all the remaining records using Delete command.
	DELETE FROM DEPOSIT_DETAIL

	SELECT * FROM DEPOSIT_DETAIL


--7. Delete all the records of Deposit_Detail table. (Use Truncate)
	TRUNCATE TABLE DEPOSIT_DETAIL

	SELECT * FROM DEPOSIT_DETAIL


--8. Remove Deposit_Detail table. (Use Drop)
	DROP TABLE DEPOSIT_DETAIL



-------PART-B

CREATE TABLE EMPLOYEE_MASTER(
	EMPNO INT,
	EMPNAME VARCHAR(25),
	JOININGDATE DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(20)
);

INSERT INTO EMPLOYEE_MASTER VALUES
	(101, 'KEYUR', '2002-01-05', 12000.00, 'RAJKOT'),
	(102, 'HARDIK', '2004-02-15', 14000.00, 'AHMEDABAD'),
	(103, 'KAJAL', '2006-03-14', 15000.00, 'BARODA'),
	(104, 'BHOOMI', '2005-06-23', 12500.00, 'AHMEDABAD'),
	(105, 'HARMIT', '2004-02-15', 14000.00, 'RAJKOT'),
	(106, 'MITESH', '2001-09-29', 5000.00, 'JAMANAGAR'),
	(107, 'MEERA', NULL, 7000.00, 'MORBI'),
	(108, 'KISHAN', '2003-02-06', 10000, NULL);

SELECT * FROM EMPLOYEE_MASTER