 =============LAB-8=============

CREATE TABLE SALES_DATA(
	REGION VARCHAR(20),
	PRODUCT VARCHAR(20),
	SALES_AMOUNT INT,
	YEAR INT
);

INSERT INTO SALES_DATA VALUES
	('NORTH AMERICA', 'WATCH', 1500, 2023),
	('EUROPE', 'MOBILE', 1200, 2023),
	('AISA', 'WATCH', 1800, 2023),
	('NORTH AMERICA', 'TV', 900, 2024),
	('EUROPE', 'WATCH', 2000, 2024),
	('AISA', 'MOBILE', 1000, 2024),
	('NORTH AMERICA', 'MOBILE', 1600, 2023),
	('EUROPE', 'TV', 1500, 2023),
	('AISA', 'TV', 1100, 2024),
	('NORTH AMERICA', 'WATCH', 1700, 2024);

SELECT * FROM SALES_DATA



-------PART-A

--1. Display Total Sales Amount by Region.
	SELECT
		REGION,
		SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
	FROM SALES_DATA
	GROUP BY REGION


--2. Display Average Sales Amount by Product
	SELECT
		PRODUCT,
		AVG(SALES_AMOUNT) AS AVG_AMOUNT
	FROM SALES_DATA
	GROUP BY PRODUCT


--3. Display Maximum Sales Amount by Year
	SELECT
		YEAR,
		MAX(SALES_AMOUNT) AS MAX_AMOUNT
	FROM SALES_DATA
	GROUP BY YEAR


--4. Display Minimum Sales Amount by Region and Year
	SELECT
		REGION,
		YEAR,
		MIN(SALES_AMOUNT) AS MIN_AMOUNT
	FROM SALES_DATA
	GROUP BY REGION, YEAR


--5. Count of Products Sold by Region
	SELECT
		REGION,
		COUNT(PRODUCT) AS COUNT_PRODUCT
	FROM SALES_DATA
	GROUP BY REGION


--6. Display Sales Amount by Year and Product
	SELECT
		SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
	FROM SALES_DATA
	GROUP BY YEAR, PRODUCT


--7. Display Regions with Total Sales Greater Than 5000